<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\JobRepresentation|\Omeka\Entity\Job|null $job
 * @var string|null $state
 * @var bool $skipCssJs
 *
 * And passed options.
 */

use Log\Stdlib\JobState;

if (!$job) return;

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

if (!$skipCssJs) {
    $assetUrl = $plugins->get('assetUrl');
    $this->headLink()->appendStylesheet($assetUrl('css/job.css', 'Log'));
    $this->headScript()->appendFile($assetUrl('js/job.js', 'Log'), 'text/javascript', ['defer' => 'defer']);
}

$jobId = method_exists($job, 'id') ? $job->id() : $job->getId();

if ($state) {
    $jobStateUrl = $url('admin/job-state', ['id' => $jobId]);
    $jobStateUrlAttr = 'data-job-state-url="' . $jobStateUrl . '"';
    $stateWarning = $escapeAttr($translate('Warning: The system state may not be reliable on some servers.'));
    $stateWarning = sprintf(' title="%1$s" aria-label="%1$s"', $stateWarning);
    $stateIcon = JobState::STATES[$state]['icon'];
    $stateLabel = $translate(JobState::STATES[$state]['label']);
    $stateLabelEsc = $escape($stateLabel);
    $stateLabelEscAttr = $escapeAttr($stateLabel);
} else {
    $stateIcon = 'no-state';
    $stateLabelEsc = $escape($translate('No system state'));
    $stateLabelEscAttr = $escapeAttr($translate('No system state'));
}
?>

<?php if ($state): ?>

<span class="job-state" data-job-id="<?= $jobId ?>" data-job-state="<?= $state ?>" <?= $jobStateUrlAttr ?> <?= $stateWarning ?>>
    <span class="system-state-label hidden"><?= $stateLabelEsc ?></span>
    <span class="system-state-icon <?= $stateIcon ?>" title="<?= $stateLabelEscAttr ?>" aria-label="<?= $stateLabelEscAttr ?>"></span>
</span>

<?php else: ?>

<span class="job-state" data-job-id="<?= $jobId ?>">
    <span class="system-state-label hidden"><?= $stateLabelEsc ?></span>
    <span class="system-state-icon no-state" title="<?= $stateLabelEscAttr ?>" aria-label="<?= $stateLabelEscAttr ?>"></span>
</span>

<?php endif; ?>
