<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string|null $html
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<dialog class="popup popup-dialog dialog-log" aria-label="<?= $escapeAttr($translate('Log details')) ?>">
    <div class="dialog-background">
        <div class="dialog-panel">
            <div class="dialog-header">
                <button type="button" class="dialog-header-close-button">
                    <span class="dialog-close" aria-hidden="true">🗙</span>
                    <span class="dialog-close-label"><?= $this->translate('Close') ?></span>
                </button>
            </div>
            <div class="dialog-contents">
                <?= $html ?? '' ?>
            </div>
            <div class="dialog-footer"></div>
        </div>
    </div>
</dialog>
